### ISSUE TITLE
issus with build android studio 3.0 

### ISSUE THREAD

**Issue by AdelBou** [bookdash/bookdash-android-app#34]
Information:Gradle tasks [:app:generateMockDebugSources, :app:generateMockDebugAndroidTestSources, :app:mockableAndroidJar, :fabbutton:generateDebugSources, :fabbutton:generateDebugAndroidTestSources, :fabbutton:mockableAndroidJar]

Error:Execution failed for task ':app:processMockDebugGoogleServices'.
> No matching client found for package name 'org.bookdash.android.qa'

**Comment by dodaithach** [comment]
Hi AdelBou,

This issue is caused by the missing **google-service.json** file. This file is generated by Firebase and it cannot be shared (you can imagine this file as the keystore file of an APK). However, if you notice, there is a **server** folder inside this project, which contains several **.json** file. These files can be imported by Firebase to generate a new database. And then you can generate a new **google-service.json** file to import to your project.

Hope this help!!!

**Comment by riggaroo** [comment]
@dodaithach is correct.
Please generate your own google-services.json file. @AdelBou

**Comment by Okezie** [comment]
Am having the same issue even though i have generated my own google-services.json file and pasted in my project. It compiles and crash with the error report "Default FirebaseApp is not initialized in this process org.bookdash.android.qa. Make sure to call FirebaseApp.initializeApp(Context) first." Any help thank you

**Comment by samsnook** [comment]
I'm having the same issue too.  I downloaded the google-services.json file from Firebase and pasted into the app folder of the Project.  Checked the package name and application Id build.gradle and Android Manifest - and they are identical to the google-services.json package_name.  

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processMockDebugGoogleServices'.
> No matching client found for package name 'org.bookdash.android.qa'

BUILD FAILED in 0s

**Comment by samsnook** [comment]
I solved it by deleting out lines 77 to 84 in the build.gradle (Project:bookdash-android-app-master).

The lines I deleted out were:
 mock {
            dimension "env"
            applicationIdSuffix ".qa"
        }
        qa {
            dimension "env"
            applicationIdSuffix ".qa"
        }

Hope this works for you!
